spring:
  application:
    name: CHAT-SERVICE
  data:
    mongodb:
      uri: "mongodb://mongo:mongo@mongodb:27017?authSource=admin"
      database: "CDM"

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://registryservice:8761/eureka/}