server:
  port: 9296

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://registryservice:8761/eureka/}

spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      # globalcors:
      #   cors-configurations:
      #     '[/**]':
      #       allowedOrigins:
      #         - "https://cdm.tuilakhanh.id.vn"
      #         - "http://localhost:5173"
      #       allowedMethods: "*"
      #       allowedHeaders: "*"
      #       allowCredentials: true
      #       maxAge: 3600
      routes:
#        - id: REGISTRY-SERVICE
#          uri: lb://REGISTRY-SERVICE
#          predicates:
#            - Path=/eureka


        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          metadata:
            cors:
              allowedOrigins:
                - "https://cdm.tuilakhanh.id.vn"
                - "http://localhost:5173"
              allowedMethods: "*"
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 3600

        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          metadata:
            cors:
              allowedOrigins:
                - "https://cdm.tuilakhanh.id.vn"
                - "http://localhost:5173"
              allowedMethods: "*"
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 3600
          filters:
            - AuthenticationFilter
#            - name: CircuitBreaker
#              args:
#                name: PRODUCT-SERVICE
#                fallbackuri: forward:/productServiceFallBack

        - id: INVENTORY-SERVICE
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - AuthenticationFilter
#            - name: CircuitBreaker
#              args:
#                name: INVENTORY-SERVICE
#                fallbackuri: forward:/inventoryServiceFallBack

        - id: ENERGY-SERVICE
          uri: lb://ENERGY-SERVICE
          predicates:
            - Path=/api/v1/energy/**
          filters:
            - AuthenticationFilter

        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter
#            - name: CircuitBreaker
#              args:
#                name: ORDER-SERVICE
#                fallbackuri: forward:/orderServiceFallBack

        - id: REPORT-SERVICE
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/v1/reports/**
          filters:
            - AuthenticationFilter
#            - name: CircuitBreaker
#              args:
#                name: REPORT-SERVICE
#                fallbackuri: forward:/reportServiceFallBack

        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter


        - id: CHAT-SERVICE
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/chat/**
          metadata:
            cors:
              allowedOrigins:
                - "https://cdm.tuilakhanh.id.vn"
                - "http://localhost:5173"
              allowedMethods: "*"
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 3600

        - id: CHAT-SERVICE-WS
          uri: lb:ws://CHAT-SERVICE
          predicates:
            - Path=/api/chatws/**

        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
          metadata:
            cors:
              allowedOrigins:
                - "https://cdm.tuilakhanh.id.vn"
                - "http://localhost:5173"
              allowedMethods: "*"
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 3600

        - id: VOUCHER-SERVICE
          uri: lb://VOUCHER-SERVICE
          predicates:
            - Path=/api/vouchers/**

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0  